### ISSUE TITLE
context must be a dict rather than Context.

### ISSUE THREAD

**Issue by itkg-ppottie** [vikingco/django-ajax-utilities#25]
https://github.com/vikingco/django-ajax-utilities/blob/master/django_ajax/templatetags/tabbing.py#L35

**Comment by Duologic** [comment]
Hi @itkg-ppottie 

Great. Can you make a pull request for this? I can ask our dev's to have look at it and make the merge.

**Comment by nielsvanoch** [comment]
Pull request merged. Thanks for helping out!
